spring:
  datasource:
    url: jdbc:mysql://10.1.1.20:3306/account_db?serverTimezone=Europe/Warsaw&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jackson:
    default-property-inclusion: non_null
account:
  default:
    active: true
    roles: ROLE_USER
security:
  jwt:
    user:
      uriLogin: /auth/login
      uriRegister: /auth/register
      header: Authorization
      prefix: Bearer
      expiration: 86400
      secret: JwtSecretKey
      authoritiesTag: authorities
      allowedIpTag: allowedIp
services.useipv4: true